development: &default
  adapter: postgresql
  database: browncoat-brass_development
  encoding: utf8
  host: localhost
  username: postgres
  password: by0BCjKz
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: browncoat-brass_test
