default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: 0243b6d537c869508a619f23de54fdea14708afb0dcbdf5fa05c6b515804f7d5ce31d6de14c27b3ef91eef21eb70befdf0893ac12aa003e1bd151b803a8d0e1b

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
